#!/bin/sh 

if [ $# != 1 ]; then
    echo "Usage: $0 <data file>"
    exit 1
fi

lsfenvfile=$1; shift
lsfreturnfile=${lsfenvfile}.lsf.ret

R --vanilla <<EOF

lsf.ret <- try({
  newenv <- environment()
  load("${lsfenvfile}", envir=newenv)
  eval(get("lsf.call", env=newenv), envir=newenv)
})

save(lsf.ret, file = "${lsfreturnfile}")

EOF

